--Table News
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Lorem ipsum', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Donec quam felis', 'ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'In enim justo', 'In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Aenean vulputate eleifend tellus', 'Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Phasellus viverra nulla', 'Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Maecenas tempus', 'Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Maecenas nec odio', 'Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Donec sodales sagittis magna', 'Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Nullam accumsan lorem in dui', 'Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Duis arcu tortor', 'Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Nunc nonummy metus', 'Vestibulum volutpat pretium libero. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede. Sed lectus. Donec mollis hendrerit risus.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Phasellus nec sem', 'Phasellus nec sem in justo pellentesque facilisis. Etiam imperdiet imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Maecenas malesuada', 'Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Vestibulum ante', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac placerat dolor lectus quis orci. Phasellus consectetuer vestibulum elit.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Aenean tellus metus', 'Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc. Vestibulum fringilla pede sit amet augue. In turpis. Pellentesque posuere. Praesent turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Donec elit libero', 'Donec elit libero, sodales nec, volutpat a, suscipit non, turpis. Nullam sagittis. Suspendisse pulvinar, augue ac venenatis condimentum, sem libero volutpat nibh, nec pellentesque velit pede quis nunc.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Vestibulum ante ipsum primis', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Ut varius tincidunt libero. Phasellus dolor. Maecenas vestibulum mollis diam. Pellentesque ut neque.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Pellentesque', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium. Pellentesque auctor neque nec urna. Proin sapien ipsum, porta a, auctor quis, euismod ut, mi.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Aenean viverra rhoncus pede', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non enim eleifend felis pretium feugiat. Vivamus quis mi. Phasellus a est. Phasellus magna. In hac habitasse platea dictumst. Curabitur at lacus ac velit ornare lobortis.');
INSERT INTO public.news(date, title, text) VALUES (current_timestamp, 'Curabitur a felis', 'Curabitur a felis in nunc fringilla tristique. Morbi mattis ullamcorper velit. Phasellus gravida semper nisi. Nullam vel sem. Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam. Sed hendrerit. Morbi ac felis.');

--Table Comment
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean commodo ligula eget dolor', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean massa', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nulla consequat massa quis enim', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam dictum felis eu pede mollis pretium', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Integer tincidunt', '1', '1');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cras dapibus', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vivamus elementum semper nisi', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean vulputate eleifend tellus', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus viverra nulla ut metus varius laoreet', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Quisque rutrum', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean imperdiet', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam ultricies nisi vel augue', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur ullamcorper ultricies nisi', '1', '2');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam eget dui', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam rhoncus', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas nec odio et ante tincidunt tempus', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec vitae sapien ut libero venenatis faucibus', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam quis ante', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam sit amet orci eget eros faucibus tincidunt', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Duis leo', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed fringilla mauris sit amet nibh', '1', '3');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec sodales sagittis magna', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce vulputate eleifend sapien', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam accumsan lorem in dui', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cras ultricies mi eu turpis hendrerit fringilla', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam pretium turpis et arcu', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed aliquam ultrices mauris', '1', '4');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent adipiscing', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus ullamcorper ipsum rutrum nunc', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc nonummy metus', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum volutpat pretium libero', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cras id dui', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean ut eros et nisl sagittis vestibulum', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed lectus', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec mollis hendrerit risus', '1', '5');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus nec sem in justo pellentesque facilisis', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam imperdiet imperdiet orci', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc nec neque', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas malesuada', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent congue erat at massa', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed cursus turpis vitae tortor', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec posuere vulputate arcu', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus accumsan cursus velit', '1', '6');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac placerat dolor lectus quis orci', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus consectetuer vestibulum elit', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum fringilla pede sit amet augue', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In turpis', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque posuere', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent turpis', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec elit libero, sodales nec, volutpat a, suscipit non, turpis', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam sagittis', '1', '7');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse pulvinar, augue ac venenatis condimentum, sem libero volutpat nibh, nec pellentesque velit pede quis nunc', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut varius tincidunt libero', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus dolor', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas vestibulum mollis diam', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque ut neque', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In dui magna, posuere eget, vestibulum et, tempor auctor, justo', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In ac felis quis tortor malesuada pretium', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque auctor neque nec urna', '1', '8');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Proin sapien ipsum, porta a, auctor quis, euismod ut, mi', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aenean viverra rhoncus pede', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut non enim eleifend felis pretium feugiat', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vivamus quis mi', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus a est', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus magna', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In hac habitasse platea dictumst', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur at lacus ac velit ornare lobortis', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur a felis in nunc fringilla tristique', '1', '9');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Morbi mattis ullamcorper velit', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus gravida semper nisi', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam vel sem', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed hendrerit', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Morbi ac felis', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc egestas, augue at pellentesque laoreet, felis eros vehicula leo, at malesuada velit leo quis pede', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec interdum, metus et hendrerit aliquet, dolor diam sagittis ligula, eget egestas libero turpis vel mi', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc nulla', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce risus nisl, viverra et, tempor et, pretium in, sapien', '1', '10');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec venenatis vulputate lorem', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Morbi nec metus', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus blandit leo ut odio', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas ullamcorper, dui et placerat feugiat, eros pede varius nisi, condimentum viverra felis nunc et lorem', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed magna purus, fermentum eu, tincidunt eu, varius ut, felis', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In auctor lobortis lacus', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum ullamcorper mauris at ligula', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce fermentum', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam cursus lacinia erat', '1', '11');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent blandit laoreet nibh', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce convallis metus id felis luctus adipiscing', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque egestas, neque sit amet convallis pulvinar, justo nulla eleifend augue, ac auctor orci leo non est', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Quisque id mi', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut tincidunt tincidunt erat', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam feugiat lorem non metus', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum dapibus nunc ac augue', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur vestibulum aliquam leo', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent egestas neque eu enim', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In hac habitasse platea dictumst', '1', '12');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce a quam', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam ut purus mattis mauris sodales aliquam', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur nisi', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Quisque malesuada placerat nisl', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed augue ipsum, egestas nec, vestibulum et, malesuada adipiscing, dui', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum facilisis, purus nec pulvinar iaculis, ligula mi congue nunc, vitae euismod ligula urna in dolor', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Mauris sollicitudin fermentum libero', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent nonummy mi in odio', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc interdum lacus sit amet orci', '1', '13');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum rutrum, mi nec elementum vehicula, eros quam gravida nisl, id fringilla neque ante vel mi', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Morbi mollis tellus ac sapien', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui, id egestas quam mauris ut lacus', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce vel dui', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed in libero ut nibh placerat accumsan', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Proin faucibus arcu quis ante', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'In consectetuer turpis ut velit', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nulla sit amet est', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent metus tellus, elementum eu, semper a, adipiscing nec, purus', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cras risus ipsum, faucibus ut, ullamcorper id, varius ac, leo', '1', '14');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse feugiat', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse enim turpis, dictum sed, iaculis a, condimentum nec, nisi', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent nec nisl a purus blandit viverra', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent ac massa at ligula laoreet iaculis', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce pharetra convallis urna', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Quisque ut nisi', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse non nisl sit amet velit hendrerit rutrum', '1', '15');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut leo', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut a nisl id ante tempus hendrerit', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Proin pretium, leo ac pellentesque mollis, felis nunc ultrices eros, sed gravida augue augue mollis justo', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse eu ligula', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nulla facilisi', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec id justo', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent porttitor, nulla vitae posuere iaculis, arcu nisl dignissim dolor, a pretium mi sem ut ipsum', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur suscipit suscipit tellus', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent vestibulum dapibus nibh', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam iaculis nunc ac metus', '1', '16');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Ut id nisl quis enim dignissim sagittis', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam sollicitudin, ipsum eu pulvinar rutrum, tellus ipsum laoreet sapien, quis venenatis ante odio sit amet eros', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Proin magna', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Duis vel nibh at velit scelerisque suscipit', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur turpis', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum suscipit nulla quis orci', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce ac felis sit amet ligula pharetra condimentum', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Maecenas egestas arcu quis ligula mattis placerat', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Duis lobortis massa imperdiet quam', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse potenti', '1', '17');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque commodo eros a enim', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed libero', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aliquam erat volutpat', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Etiam vitae tortor', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Morbi vestibulum volutpat enim', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aliquam eu nunc', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nunc sed turpis', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed mollis, eros et ultrices tempus, mauris ipsum aliquam libero, non adipiscing dolor urna a orci', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nulla porta dolor', '1', '18');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Pellentesque dapibus hendrerit tortor', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Praesent egestas tristique nibh', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Sed a libero', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Cras varius', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec vitae orci sed dolor rutrum auctor', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce egestas elit eget lorem', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse nisl elit, rhoncus eget, elementum ac, condimentum eget, diam', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam at tortor in tellus interdum sagittis', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Aliquam lobortis', '1', '19');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Donec orci lectus, aliquam ut, faucibus non, euismod id, nulla', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Curabitur blandit mollis lacus', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nam adipiscing', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vestibulum eu odio', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Vivamus laoreet', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Nullam tincidunt adipiscing enim', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Phasellus tempus', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Fusce neque', '1', '20');
INSERT INTO public.comment(date, text, user_id, news_id) VALUES (current_timestamp, 'Suspendisse faucibus, nunc et pellentesque egestas, lacus ante convallis tellus, vitae iaculis lacus elit id tortor', '1', '20');