server:
  port: 8081

spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  jackson:
    time-zone: Europe/Minsk

  cache:
    cache-names: news, comments
    caffeine:
      spec: maximumSize=10, expireAfterWrite=1m

springdoc:
  swagger-ui:
    path: /index.html
    url: /swagger/openapi.yaml
    operations-sorter: method
    default-models-expand-depth: -1
