server:
  port: 8081

spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  jackson:
    time-zone: Europe/Minsk

springdoc:
  swagger-ui:
    path: /index.html
    url: /swagger/openapi.yaml
    operations-sorter: method
    default-models-expand-depth: -1
